corporate_services/icl_corporate_services/report/employee_information/employee_information.json, corporate_services/icl_corporate_services/report/leave_management/leave_management.json
@brianraila Creation of the employee information report.
=> Employee information

corporate_services/icl_corporate_services/report/leave_management/leave_management.json
@brianraila Creation of leave management report
=> creation of leave management report

corporate_services/icl_corporate_services/report/employee_information/employee_information.json, corporate_services/icl_corporate_services/report/job_management/job_management.json, corporate_services/icl_corporate_services/report/leave_management/leave_management.json
@brianraila creation of the job management report
=> Job management

corporate_services/fixtures/client_script.json, corporate_services/hooks.py
@brianraila Re-update three client scripts
- Travel Request Filters / Travel Request Actions
- Work Continuity Plan
=> Clients scripts update

corporate_services/hooks.py
- Identified as source of bug when creating Leave Application
=> [fix] - Remove hooks for leave application

corporate_services/icl_corporate_services/workspace/home/home.json, corporate_services/icl_corporate_services/workspace/icl_hr_admin/icl_hr_admin.json, corporate_services/icl_corporate_services/workspace/icl_project_manager/icl_project_manager.json, corporate_services/icl_corporate_services/workspace/icl_staff/icl_staff.json, corporate_services/icl_corporate_services/workspace/icl_supervisor/icl_supervisor.json, corporate_services/icl_corporate_services/workspace/welcome_workspace/welcome_workspace.json
@brianraila Creation of workspaces roles.
=> Creation of workspaces roles.

corporate_services/icl_corporate_services/workspace/home/home.json, corporate_services/icl_corporate_services/workspace/icl_hr_admin/icl_hr_admin.json, corporate_services/icl_corporate_services/workspace/icl_project_manager/icl_project_manager.json, corporate_services/icl_corporate_services/workspace/icl_staff/icl_staff.json, corporate_services/icl_corporate_services/workspace/icl_supervisor/icl_supervisor.json, corporate_services/icl_corporate_services/workspace/welcome_workspace/welcome_workspace.json
@brianraila 
- Different users can only see specific workspaces.
=> Update of permission role manager for the workspaces

corporate_services/hooks.py
@brianraila creation of dynamic notifications
=> creation of dynamic notifications

corporate_services/api/role/user.py, corporate_services/fixtures/client_script.json
@brianraila Asset movement filter to only display the employee with the role finance.
=> Asset movement filter to only display the employee with the role finance

corporate_services/api/role/user.py, corporate_services/api/timesheet/timesheet_import.py, corporate_services/fixtures/client_script.json, corporate_services/hooks.py, corporate_services/icl_corporate_services/doctype/timesheet_submission/timesheet_submission.json, corporate_services/icl_corporate_services/doctype/timesheet_submission_list/timesheet_submission_list.json, corporate_services/icl_corporate_services/doctype/timesheet_submission_list/timesheet_submission_list.py
@brianraila Continuous progress of timesheet submission and creation of timesheet per project
=> Timesheet submission progress

corporate_services/api/notification/notifications.py, corporate_services/api/notification/work_continuity_plan.py, corporate_services/hooks.py
@brianraila work continuity plan notification integration
=> work continuity plan notification integration

corporate_services/api/notification/leave_application.py
@brianraila Missing leave application commit
=> Missing leave application commit

corporate_services/icl_corporate_services/doctype/project_manager/project_manager.json, corporate_services/icl_corporate_services/doctype/project_manager/project_manager.py
@brianraila addition of project managers child table on the project doctype
=> addition of project managers child table on the project doctype

corporate_services/api/notification/project/project_manager.py, corporate_services/hooks.py, corporate_services/icl_corporate_services/doctype/project_manager/project_manager.json, corporate_services/icl_corporate_services/doctype/project_manager/project_manager.py
@brianraila configuration of project manager notification
=> Project manager notification

corporate_services/fixtures/workflow.json, corporate_services/fixtures/workflow_state.json
@brianraila  timesheet submission workflow (fix)
=> timesheet submission workflow

corporate_services/api/timesheet/timesheet_import.py
@brianraila import timesheet try fix
=> import timesheet try fix

corporate_services/api/timesheet/timesheet_generation_export.py
@brianraila fixing the error on timesheet generation
=> fixing the error on timesheet generation

corporate_services/api/timesheet/timesheet_import.py
@brianraila Though Total hours are less than {} minimum hours.
=> Though Total hours are less than {} minimum hours.

corporate_services/api/timesheet/timesheet_generation_export.py, corporate_services/api/timesheet/timesheet_import.py
@brianraila Timesheet UI update import
=> Timesheet UI update import

corporate_services/api/notification/asset_requisition.py, corporate_services/api/notification/timesheet.py, corporate_services/api/timesheet/before_workflow_action.py, corporate_services/hooks.py
@brianraila Hooks update notifications timesheet
=> Hooks update notifications timesheet

corporate_services/api/notification/asset_requisition.py, corporate_services/hooks.py
@brianraila update of the hooks map methods to allow notifications.
=> update of the hooks map methods

corporate_services/api/role/get_role.py, corporate_services/fixtures/client_script.json
@brianraila Employee permission role manager (reduced the ability on other employees to see personal and confidential details of an employee)
=> Employee permission role manager

corporate_services/api/projects/budget_tracker_analysis.py, corporate_services/icl_corporate_services/doctype/budget_tracker_analysis/budget_tracker_analysis.json, corporate_services/icl_corporate_services/doctype/budget_tracker_analysis/budget_tracker_analysis.py
@brianraila missing budget tracker analysis doctype
=> missing budget tracker analysis

corporate_services/api/project/payment_entry.py, corporate_services/hooks.py
@brianraila Fetching Budget line data from the payment entry, for a specific project.
=> Fetching Budget line data from the payment entry, for a specific project

corporate_services/fixtures/workflow.json, corporate_services/fixtures/workflow_state.json
@brianraila 
- workflow update and workflow states.
I had left out these two on my previous pull request
=> workflow update and workflow states

corporate_services/fixtures/client_script.json, corporate_services/fixtures/workspace.json, corporate_services/icl_corporate_services/custom/asset_movement.json, corporate_services/icl_corporate_services/workspace/icl_staff/icl_staff.json
@brianraila 
- New Asset Damage Loss Theft Report Form
=> New Asset Damage Loss Theft Report Form

corporate_services/icl_corporate_services/doctype/timesheet_submission/timesheet_submission.json
@brianraila timesheet feedback on the filter UI
=> timesheet feedback

corporate_services/api/import_coa.py, corporate_services/hooks.py
@brianraila 
- corporate services chart of accounts importation.
=> corporate services chart of accounts importation

corporate_services/api/timesheet/timesheet_generation_export.py, corporate_services/icl_corporate_services/workspace/icl_finance/icl_finance.json
@brianraila 
- removal of the yellow color on the timesheet.
=> removal of the yellow color on the timesheet

corporate_services/api/leave/update_annual_leave_allocations.py, corporate_services/hooks.py
@brianraila create new year leave allocations
=> create new year leave allocations

corporate_services/api/timesheet/timesheet_generation_export.py, corporate_services/api/timesheet/timesheet_import.py
Adding the blue fill color to the total row and the introduction of a total row calculation
=> Adding the blue fill color to the total row and ui update

corporate_services/api/timesheet/timesheet_generation_export.py, corporate_services/api/timesheet/timesheet_import.py, corporate_services/icl_corporate_services/workspace/icl_finance/icl_finance.json
@brianraila Introduction of the per diem rates on the finance dashboard
=> Finance dashboard update

corporate_services/fixtures/workspace.json
@brianraila - Introduction of the Business development **workspace** responsible for the project bidding processes.
=> Introduction of the Business development workspace responsible for the project bidding processes.

corporate_services/fixtures/workspace.json
@brianraila update of the project manager workspace with the billing form shortcut
=> update of the project manager workspace

corporate_services/api/leave/update_annual_leave_allocations.py, corporate_services/icl_corporate_services/doctype/contract_type/contract_type.json
@brianraila Get employees who are eligible for leave allocation based on contract type
Returns list of employees whose contract type has accumulate_monthly_leave checked
=> Get employees who are eligible for leave allocation based on contract type
